name: Continious Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SBT
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run Linters and Tests
        run: sbt clean compile scalafmtCheckAll scalafmtSbtCheck test
